DDT-991: RequestedEquipmentEquipment
dcsaorg/DCSA-BKG pull request #90
Opened 2022-04-08 16:01 UTC by mp-assco

Dependent on: https://github.com/dcsaorg/DCSA-Information-Model/pull/253 and https://github.com/dcsaorg/DCSA-Event-Core/pull/292

2022-04-14 10:07 UTC, pimg requested changes

2022-04-14 10:07 UTC, pimg commented on src/main/java/org/dcsa/bkg/service/impl/BKGServiceImpl.java
> +    if (requestedEquipments.stream()
mixes streams and Reactor. Suggest rewriting this with Reactor only, that way in Reactive Stream can be used consolidating this validation, the mapping and the saving.

2022-04-14 10:07 UTC, pimg commented on src/main/java/org/dcsa/bkg/service/impl/BKGServiceImpl.java
> +                      optionalInMono(
Although not fully in scope of this story, consider refactoring Mono<Optional<List< to Mono<List< to adhere to new coding practices.

2022-04-20 11:48 UTC, pimg approved these changes

2022-04-20 11:58 UTC, FinnAtAsseco approved these changes

2022-04-20 11:59 UTC, merged